let cards = [
    {
        id: 1,
        name: "Eloise Dooley",
        gener: "female",
        jobs: "Mathematics",
        workTime: "5",
        people: "33",
        rating: "3.9",
        number: "1-692-739-8937 x25831",
        email: "Eloise.Dooley51@hotmail.com",
        telegram: "@eloisedooley",
        in: "linkedin.com/in/eloise-dooley",
        url: "https://avatars.githubusercontent.com/u/24484197"
    },
    {
        id: 2,
        name: "Spencer Kohler",
        gener: "male",
        jobs: "Computer Science",
        workTime: "20",
        people: "48",
        rating: "4.5",
        number: "(689) 829-8004",
        email: "Spencer.Kohler@hotmail.com",
        telegram: "@spencerkohler",
        in: "linkedin.com/in/spencer-kohler",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/83.jpg"
    },
    {
        id: 3,
        name: "Jessica Howe",
        jobs: "Geography",
        gener: "female",
        workTime: "27",
        people: "49",
        rating: "3.5",
        number: "545-734-2932 x86872",
        email: "Jessica.Howe@hotmail.com",
        telegram: "@jessicahowe",
        in: "linkedin.com/in/jessica-howe",
        url: "https://avatars.githubusercontent.com/u/29740210"
    },
    {
        id: 4,
        name: "Ian Bogisich",
        gener: "female",
        jobs: "History",
        workTime: "23",
        people: "41",
        rating: "3.5",
        number: "1-343-362-9323 x998",
        email: "Ian.Bogisich36@gmail.com",
        telegram: "@ianbogisich",
        in: "linkedin.com/in/ian-bogisich",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/93.jpg"
    },
    {
        id: 5,
        name: "Rafael Parisian",
        jobs: "Physical Education",
        workTime: "6",
        people: "57",
        gener: "male",
        rating: "3.6",
        number: "246.998.5666 x28543",
        email: "Rafael_Parisian6@hotmail.com",
        telegram: "@rafaelparisian",
        in: "linkedin.com/in/rafael-parisian",
        url: "https://avatars.githubusercontent.com/u/6630256"
    },
    {
        id: 6,
        name: "Olga Hamill",
        jobs: "Physical Education",
        gener: "male",
        workTime: "3",
        people: "24",
        rating: "3.7",
        number: "738.551.1613 x1507",
        email: "Olga.Hamill@gmail.com",
        telegram: "@olgahamill",
        in: "linkedin.com/in/olga-hamill",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/25.jpg"
    },
    {
        id: 7,
        name: "Erin Heidenreich",
        jobs: "Biology",
        gener: "female",
        workTime: "15",
        people: "44",
        rating: "4.7",
        number: "527-426-6491 x963",
        email: "Erin.Heidenreich58@gmail.com",
        telegram: "@erinheidenreich",
        in: "linkedin.com/in/erin-heidenreich",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/77.jpg"
    },
    {
        id: 8,
        name: "Mitchell Welch-Grady",
        jobs: "Physics",
        gener: "male",
        workTime: "26",
        people: "52",
        rating: "3.5",
        number: "(364) 356-2512",
        email: "Mitchell.Welch-Grady@hotmail.com",
        telegram: "@mitchellwelch-grady",
        in: "linkedin.com/in/mitchell-welch-grady",
        url: "https://avatars.githubusercontent.com/u/97656135"
    },
    {
        id: 9,
        name: "Angelina Hayes",
        jobs: "Music",
        gener: "female",
        workTime: "7",
        people: "37",
        rating: "3.8",
        number: "566.930.2266 x130",
        email: "Angelina.Hayes49@gmail.com",
        telegram: "@angelinahayes",
        in: "linkedin.com/in/angelina-hayes",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/12.jpg"
    },
    {
        id: 10,
        name: "Kerry Schmidt",
        jobs: "Spanish",
        gener: "male",
        workTime: "9",
        people: "35",
        rating: "4.6",
        number: "462.522.7596 x2654",
        email: "Kerry_Schmidt@yahoo.com",
        telegram: "@kerryschmidt",
        in: "linkedin.com/in/kerry-schmidt",
        url: "https://avatars.githubusercontent.com/u/29044518"
    },
    {
        id: 11,
        name: "Whitney Koepp",
        jobs: "Physical Education",
        gener: "female",
        workTime: "2",
        people: "53",
        rating: "5",
        number: "527-903-1032",
        email: "Whitney_Koepp74@yahoo.com",
        telegram: "@whitneykoepp",
        in: "linkedin.com/in/whitney-koepp",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/25.jpg"
    },
    {
        id: 12,
        name: "Rolando Crist",
        jobs: "Physical Education",
        gener: "male",
        workTime: "18",
        people: "33",
        rating: "4.6",
        number: "444.596.8832 x695",
        email: "Rolando_Crist2@gmail.com",
        telegram: "@rolandocrist",
        in: "linkedin.com/in/rolando-crist",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/26.jpg"
    },
    {
        id: 13,
        name: "Carrie Ziemann",
        jobs: "Physical Education",
        gener: "male",
        workTime: "25",
        people: "48",
        rating: "4.3",
        number: "1-782-848-4797 x45756",
        email: "Carrie_Ziemann@yahoo.com",
        telegram: "@carrieziemann",
        in: "linkedin.com/in/carrie-ziemann",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/35.jpg"
    },
    {
        id: 14,
        name: "Isabel DuBuque",
        gener: "female",
        jobs: "Biology",
        workTime: "19",
        people: "30",
        rating: "4.6",
        number: "412.777.6093 x82111",
        email: "Isabel.DuBuque2@yahoo.com",
        telegram: "@isabeldubuque",
        in: "linkedin.com/in/isabel-dubuque",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/22.jpg"
    },
    {
        id: 15,
        name: "Smitham Neil",
        jobs: "Music",
        workTime: "15",
        gener: "male",
        people: "49",
        rating: "3.7",
        number: "(311) 932-8191 x106",
        email: "Neil.Smitham@hotmail.com",
        telegram: "@neilsmitham",
        in: "linkedin.com/in/neil-smitham",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/4.jpg"
    },
    {
        id: 16,
        name: "Carmen Hand",
        jobs: "Music",
        workTime: "20",
        gener: "male",
        people: "53",
        rating: "3.7",
        number: "217-452-2798 x33913",
        email: "Carmen_Hand32@yahoo.com",
        telegram: "@carmenhand",
        in: "linkedin.com/in/carmen-hand",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/10.jpg"
    },
    {
        id: 17,
        name: "Kevin Murray-Heathcote",
        jobs: "Physics",
        gener: "male",
        workTime: "29",
        people: "54",
        rating: "4.9",
        number: "1-220-660-4171 x342",
        email: "Kevin.Murray-Heathcote@gmail.com",
        telegram: "@kevinmurray-heathcote",
        in: "linkedin.com/in/kevin-murray-heathcote",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/52.jpg"
    },
    {
        id: 18,
        name: "Julio Rath",
        gener: "male",
        jobs: "Physics",
        workTime: "1",
        people: "59",
        rating: "3.8",
        number: "(276) 804-2075",
        email: "Julio.Rath@yahoo.com",
        telegram: "@juliorath",
        in: "linkedin.com/in/julio-rath",
        url: "https://avatars.githubusercontent.com/u/90551479"
    },
    {
        id: 19,
        name: "Robyn VonRueden",
        jobs: "PhysiPhysical Educationcs",
        gener: "male",
        workTime: "9",
        people: "43",
        rating: "3.9",
        number: "598-812-9414",
        email: "Robyn.VonRueden@yahoo.com",
        telegram: "@robynvonrueden",
        in: "linkedin.com/in/robyn-vonrueden",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/52.jpg"
    },
    {
        id: 20,
        name: "Elizabeth Stoltenberg",
        jobs: "Mathematics",
        workTime: "15",
        people: "25",
        gener: "female",
        rating: "3.7",
        number: "422.479.4831 x298",
        email: "Elizabeth_Stoltenberg@gmail.com",
        telegram: "@elizabethstoltenberg",
        in: "linkedin.com/in/elizabeth-stoltenberg",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/90.jpg"
    },
    {
        id: 21,
        name: "Chris Parker",
        jobs: "Physical Education",
        workTime: "2",
        people: "44",
        gener: "male",
        rating: "3.5",
        number: "1-778-716-8425 x70497",
        email: "Chris_Parker82@hotmail.com",
        telegram: "@chrisparker",
        in: "linkedin.com/in/chris-parker",
        url: "https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/10.jpg"
    },
    {
        id: 22,
        name: "Jody Gottlieb",
        jobs: "English Literature",
        workTime: "37",
        gener: "female",
        people: "34",
        rating: "3.9",
        number: "927.812.5948 x210",
        email: "Jody.Gottlieb@gmail.com",
        telegram: "@jodygottlieb",
        in: "linkedin.com/in/jody-gottlieb",
        url: "https://avatars.githubusercontent.com/u/33202453"
    },
    {
        id: 23,
        name: "Ernestine Franey",
        jobs: "Mathematics",
        workTime: "1",
        people: "41",
        gener: "female",
        rating: "4.5",
        number: "647-882-7302 x7634",
        email: "Ernestine_Franey22@yahoo.com",
        telegram: "@ernestinefraney",
        in: "linkedin.com/in/ernestine-franey",
        url: "https://avatars.githubusercontent.com/u/17588763"
    },
    {
        id: 24,
        name: "Schuster Schuster",
        jobs: "Mathematics",
        workTime: "12",
        people: "44",
        gener: "female",
        rating: "4.5",
        number: "202-805-8160 x04869",
        email: "Jasmine.Schuster@yahoo.com",
        telegram: "@jasmineschuster",
        in: "linkedin.com/in/jasmine-schuster",
        url: "https://avatars.githubusercontent.com/u/34391677"
    },


]